services:
    devcontainer:
        image: kakkoii1337/gai_devcontainer:1.0.153
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile.devcontainer
            args:
                VARIANT: "3.10-bullseye"
                NODE_VERSION: "21.1.0"
                USERNAME: "kakkoii1337"
                CACHE_BUST: "1.0.153"
        ports:
            - "12033:12033"
        environment:
            LOG_LEVEL: "DEBUG"
        volumes:
            # Make sure this matches the workspaceFolder in .devcontainer/devcontainer.json
            - $HOME/.gai:/$HOME/.gai
            - ..:/workspaces/gai:cached
            - /var/run/docker.sock:/var/run/docker.sock
        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity

    gai-ttt-svr:
        image: kakkoii1337/gai-ttt-svr-llamacpp:1.0.10
        container_name: gai-ttt-svr
        environment:
            DEFAULT_GENERATOR: "ttt-llamacpp-dolphin"
            MAX_SEQ_LEN: "6000"
            LOG_LEVEL: "DEBUG"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
        volumes:
            - ~/.gai:/root/.gai
        ports:
            - "12031:12031"
            - "5678:5678"
        restart: always
        command: python -m debugpy --listen 0.0.0.0:5678 main.py

    # gai-ttt-svr:
    #     image: kakkoii1337/gai-ttt-svr-exllamav2:1.0.51
    #     container_name: gai-ttt-svr
    #     environment:
    #         DEFAULT_GENERATOR: "ttt-exllamav2-dolphin"
    #         MAX_SEQ_LEN: "8192"
    #         LOG_LEVEL: "DEBUG"
    #     deploy:
    #         resources:
    #             reservations:
    #                 devices:
    #                     - driver: nvidia
    #                       capabilities: [gpu]
    #     volumes:
    #         - ~/.gai:/root/.gai
    #     ports:
    #         - "12031:12031"
    #         - "5678:5678"
    #     restart: always
    #     command: python -m debugpy --listen 0.0.0.0:5678 main.py

    gai-tti-svr:
        image: kakkoii1337/gai-tti-svr:1.0.9
        container_name: gai-tti-svr
        environment:
            CLI_ARGS: "--listen --api --xformers --medvram --no-download-sd-model --ckpt /stable-diffusion-webui/models/Stable-diffusion/runwayml/v1-5-pruned-emaonly.safetensors"
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
                          driver: nvidia
                          count: all
        ports:
            - "12035:12035"
        volumes:
            - ~/.gai/models/Stable-diffusion:/stable-diffusion-webui/models/Stable-diffusion
            - ~/.gai/models/VAE:/stable-diffusion-webui/models/VAE

    # gai-rag-svr:
    #     image: kakkoii1337/gai-rag-svr:1.0.18
    #     container_name: gai-rag-svr
    #     environment:
    #         DEFAULT_GENERATOR: "rag-instructor-sentencepiece"
    #         LOG_LEVEL: "DEBUG"
    #         TZ: "Asia/Singapore"
    #         SWAGGER_URL: "/doc"
    #     deploy:
    #         resources:
    #             reservations:
    #                 devices:
    #                     - driver: nvidia
    #                       capabilities: [gpu]
    #     volumes:
    #         - ~/.gai:/root/.gai
    #     ports:
    #         - "12036:12036"
    #         - "5679:5679"
    #     restart: always
    #     command: python -m debugpy --listen 0.0.0.0:5679 main.py

    nats01:
        image: nats:latest
        container_name: nats01
        ports:
            - "4222:4222" # Client port
            - "8222:8222" # Monitoring port
            - "6222:6222" # Cluster port
        command:
            - "--cluster"
            - "nats://0.0.0.0:6222"
            # - "--routes"
            # - "nats://nats02:6223"
            # - "--routes"
            # - "nats://nats03:6224"
        restart: unless-stopped

    gaimace-node-02:
        image: kakkoii1337/gaimace:1.0.83
        container_name: gaimace-node-02
        environment:
            LOG_LEVEL: "INFO"
            GAIMACE_MODE: "node"
            GAIMACE_PERSONA: "Diana"
            GAIMACE_NATS: "nats://nats01:4222"
            GAIMACE_TTT: "http://gai-ttt-svr:12031"
            GAIMACE_RAG: "http://gai-rag-svr:12036"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
        restart: always

    gaimace-node-03:
        image: kakkoii1337/gaimace:1.0.83
        container_name: gaimace-node-03
        environment:
            LOG_LEVEL: "INFO"
            GAIMACE_MODE: "node"
            GAIMACE_PERSONA: "George"
            GAIMACE_NATS: "nats://nats01:4222"
            GAIMACE_TTT: "http://gai-ttt-svr:12031"
            GAIMACE_RAG: "http://gai-rag-svr:12036"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
        restart: always
